### ISSUE TITLE
Cannot Resolve Symbol 'I2cDeviceSynch'

### ISSUE THREAD

**Issue by luciengaitskell** [SwerveRobotics/ftc_app#85] opened 2016-03-06 02:49 UTC
I just pulled from this repository to my fork of ftctechnh/ftc_app. The `II2cDeviceClient` class is complaining that it: `Cannot Resolve Symbol 'I2cDeviceSynch'`. How would I fix this?

**Comment by rgatkinson** [comment] 2016-03-06 02:52
You need to 'import com.qualcomm.robotcore.hardware.I2cDeviceSynch;'

Odd that this isn't happening automatically, though. Have you rebuilt since you pulled?

**Comment by luciengaitskell** [comment] 2016-03-06 03:00
Didn't rebuild my project... Whoops, thanks again!

**Comment by sgeffner22** [comment] 2016-03-06 19:23
I'm experiencing a similar problem in Darrell's swerveteams repo. Android Studio isn't finding robotcore in 'import com.qualcomm.robotcore.hardware.I2cDeviceSynch'. Did a clean build on each project but still isn't resolved. Could our build.gradle be missing something? It has these dependencies:

dependencies {
    compile files('libs/android-support-v4.jar')
    compile (name:'RobotCore-release', ext:'aar')
    compile (name:'Hardware-release', ext:'aar')
    compile (name:'FtcCommon-release', ext:'aar')
    compile (name:'ModernRobotics-release', ext:'aar')
    compile (name:'Analytics-release', ext:'aar')
    compile (name:'WirelessP2p-release', ext:'aar')
    compile project(':SwerveRoboticsLibrary')
}

**Comment by rgatkinson** [comment] 2016-03-06 19:26
Is there a repo/branch i could sync to to investigate?

**Comment by sgeffner22** [comment] 2016-03-06 19:27
https://github.com/eukota/ftc_app     the SwerveTeams branch

**Comment by sgeffner22** [comment] 2016-03-06 19:28
whoops, let me commit my changes ... which will break everyone for a little while...

**Comment by sgeffner22** [comment] 2016-03-06 19:28
ok, it's ready

**Comment by rgatkinson** [comment] 2016-03-06 19:34
I cloned that, imported into Android Studio, and it built cleanly. Ugh.

**Comment by rgatkinson** [comment] 2016-03-06 19:34
Oh! Wrong branch...wait a sec...

**Comment by rgatkinson** [comment] 2016-03-06 20:07
This is a stinker!

**Comment by rgatkinson** [comment] 2016-03-06 20:14
I'm beginning to suspect it's an issue with the .iml files being in the SCC tree.

**Comment by rgatkinson** [comment] 2016-03-06 20:39
Nope. Not that: they're not checked into the tree (which is correct). It's not parsing the imports correctly for some dang reason. I once simplified things enough to get that working, but now need to make that reproducible.

**Comment by rgatkinson** [comment] 2016-03-06 21:23
Ok. Fixed and pushed. It was an issue in AndroidStudio / gradle: we tickled a bug of theirs. Updating to track the breaking changes in the release seems to have fixed things.

**Comment by cmacfarl** [comment] 2016-03-06 21:27
Where'd you push this to?  I can't find any commit(s) from today in any of your branches.

**Comment by rgatkinson** [comment] 2016-03-06 21:29
It was our internal team's code; there were no changes in the Swerve Library itself. Rather, I updated our internal code to track 1.5.0, and the dependency analysis bugs we apparently were tickling in Android Studio went away.

**Comment by sgeffner22** [comment] 2016-03-06 21:31
Awesome, much thanks Bob! Works great now. 
Also, thanks for migrating the current sensor code to 1.5 for me!

**Closed by sgeffner22** 2016-03-06 21:31 UTC
